# Build args: PYTHON_VERSION (e.g. 3.10.20) is the only required input.
# PYTHON_MINOR (e.g. 3.10) is derived by build.sh / the workflow and passed in
# so it can be used in COPY --from paths (which require build-time literals).
ARG PYTHON_VERSION=3.10.19
ARG PYTHON_MINOR=3.10
# pyenv is pinned to a release tag so the upstream python-build definitions
# we consume are reproducible.
ARG PYENV_REF=v2.6.28

FROM centos:6 AS openssl_sqlite_builder
ARG PYTHON_VERSION
ARG PYTHON_MINOR
ARG PYENV_REF

# CentOS 6 reached EOL, so we need to use vault.centos.org
RUN sed -i 's|^mirrorlist=|#mirrorlist=|g' /etc/yum.repos.d/CentOS-Base.repo && \
  sed -i 's|^#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-Base.repo

# Install SCL repository for newer GCC and rewrite its repo file to point at
# vault.centos.org. The repo body is written via printf rather than a heredoc
# so this Dockerfile parses correctly under non-BuildKit builders (kaniko,
# classic docker build) which don't understand heredocs spanning multiple
# Dockerfile lines.
RUN yum install -y centos-release-scl && \
  rm -f /etc/yum.repos.d/CentOS-SCLo-scl*.repo && \
  printf '%s\n' \
    '[centos-sclo-rh]' \
    'name=CentOS-6 - SCLo rh' \
    'baseurl=https://vault.centos.org/6.10/sclo/x86_64/rh/' \
    'gpgcheck=1' \
    'enabled=1' \
    'gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-SCLo' \
    '' \
    '[centos-sclo-sclo]' \
    'name=CentOS-6 - SCLo sclo' \
    'baseurl=https://vault.centos.org/6.10/sclo/x86_64/sclo/' \
    'gpgcheck=1' \
    'enabled=1' \
    'gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-SCLo' \
    > /etc/yum.repos.d/CentOS-SCLo-scl.repo && \
  yum clean all

# Install build dependencies and devtoolset-7 (GCC 7).
# Python 3.10 requires GCC 4.8+ and CentOS 6 only has GCC 4.4 by default.
RUN yum install -y \
  devtoolset-7-gcc \
  devtoolset-7-gcc-c++ \
  make \
  git \
  wget \
  curl \
  tar \
  bzip2 \
  xz \
  patch \
  perl \
  zlib-devel \
  bzip2-devel \
  sqlite-devel \
  libffi-devel \
  libuuid-devel \
  readline-devel \
  ncurses-devel \
  gdbm-devel \
  xz-devel && \
  yum clean all

RUN mkdir -p /opt/python${PYTHON_MINOR}

# Clone pyenv at a pinned release tag so upstream python-build defs are reproducible.
RUN git clone --branch "${PYENV_REF}" --depth=1 https://github.com/pyenv/pyenv.git /opt/pyenv && \
  ln -s /opt/pyenv/plugins/python-build/bin/python-build /usr/local/bin/python-build

# Generate the relocatable build definition by concatenating our preamble
# (env vars pointing the build at our /opt/python${PYTHON_MINOR}/{lib,include}
# where we install OpenSSL 1.1.1 and SQLite below, plus --enable-shared) on top
# of the upstream pyenv definition for ${PYTHON_VERSION}. Upstream's
# prefer_openssl3 / mac install_package calls are inert on Linux, so plain
# concatenation is sufficient.
RUN set -e; \
  UPSTREAM=/opt/pyenv/plugins/python-build/share/python-build/${PYTHON_VERSION}; \
  if [ ! -f "${UPSTREAM}" ]; then \
    echo "ERROR: pyenv ${PYENV_REF} has no definition for Python ${PYTHON_VERSION} at ${UPSTREAM}" >&2; \
    exit 1; \
  fi; \
  DEF=/opt/pyenv/plugins/python-build/share/python-build/${PYTHON_VERSION}-c6-relocatable; \
  { \
    echo '# Generated by python-centos6-builder Dockerfile.'; \
    echo "# Wraps upstream pyenv ${PYENV_REF} definition for Python ${PYTHON_VERSION}."; \
    echo 'export PYTHON_BUILD_CONFIGURE_WITH_OPENSSL=1'; \
    echo 'export PYTHON_CFLAGS="-DOPENSSL_NO_SSL3${PYTHON_CFLAGS:+ $PYTHON_CFLAGS}"'; \
    echo 'export PYTHON_CONFIGURE_OPTS="--enable-shared --with-ensurepip=install${PYTHON_CONFIGURE_OPTS:+ $PYTHON_CONFIGURE_OPTS}"'; \
    echo "export CPPFLAGS=\"-I/opt/python${PYTHON_MINOR}/include\""; \
    echo "export PKG_CONFIG_PATH=\"/opt/python${PYTHON_MINOR}/lib/pkgconfig\""; \
    echo "export LD_LIBRARY_PATH=\"/opt/python${PYTHON_MINOR}/lib\""; \
    echo 'prefer_openssl11'; \
    echo ''; \
    cat "${UPSTREAM}"; \
  } > "${DEF}"; \
  echo "--- generated ${DEF} ---"; \
  cat "${DEF}"

# Build SQLite 3 (CentOS 6 has 3.6.20, but Python 3.10 needs 3.7.15+)
RUN cd /tmp && \
  wget https://www.sqlite.org/2024/sqlite-autoconf-3450200.tar.gz && \
  tar xzf sqlite-autoconf-3450200.tar.gz && \
  cd sqlite-autoconf-3450200 && \
  scl enable devtoolset-7 "./configure --prefix=/opt/python${PYTHON_MINOR}" && \
  scl enable devtoolset-7 "make -j$(nproc)" && \
  scl enable devtoolset-7 "make install" && \
  cd /tmp && rm -rf sqlite-autoconf-3450200*

# Build OpenSSL 1.1.1w (Python 3.10 requires OpenSSL 1.1.1+, CentOS 6 has 1.0.x)
RUN cd /tmp && \
  wget https://www.openssl.org/source/openssl-1.1.1w.tar.gz && \
  tar xzf openssl-1.1.1w.tar.gz && \
  cd openssl-1.1.1w && \
  scl enable devtoolset-7 "./config --prefix=/opt/python${PYTHON_MINOR} --openssldir=/opt/python${PYTHON_MINOR}/ssl shared zlib" && \
  scl enable devtoolset-7 "make -j$(nproc)" && \
  scl enable devtoolset-7 "make install_sw" && \
  cd /tmp && rm -rf openssl-1.1.1w*

# Build libxml2 + libxslt for lxml. CentOS 6 ships libxml2 2.7.6 (2009), far too
# old to compile a modern lxml against (its etree.c references XML_WITH_ICU /
# XML_WITH_LZMA, absent in 2.7.6). We build current versions into the prefix as
# shared libs, exactly like OpenSSL/SQLite above, so relocate.py rewrites their
# RPATHs and the lxml built against them in the pip stage is bundled and fully
# relocatable. libxslt is built --without-crypto to avoid a libgcrypt dependency
# that lxml does not need; iconv comes from glibc, and zlib/lzma from the -devel
# packages already installed above.
RUN cd /tmp && \
  wget https://download.gnome.org/sources/libxml2/2.12/libxml2-2.12.9.tar.xz && \
  echo "59912db536ab56a3996489ea0299768c7bcffe57169f0235e7f962a91f483590  libxml2-2.12.9.tar.xz" | sha256sum -c - && \
  tar xJf libxml2-2.12.9.tar.xz && \
  cd libxml2-2.12.9 && \
  scl enable devtoolset-7 "./configure --prefix=/opt/python${PYTHON_MINOR} --without-python --with-zlib --with-lzma --disable-static" && \
  scl enable devtoolset-7 "make -j$(nproc)" && \
  scl enable devtoolset-7 "make install" && \
  cd /tmp && rm -rf libxml2-2.12.9*

RUN cd /tmp && \
  wget https://download.gnome.org/sources/libxslt/1.1/libxslt-1.1.42.tar.xz && \
  echo "85ca62cac0d41fc77d3f6033da9df6fd73d20ea2fc18b0a3609ffb4110e1baeb  libxslt-1.1.42.tar.xz" | sha256sum -c - && \
  tar xJf libxslt-1.1.42.tar.xz && \
  cd libxslt-1.1.42 && \
  scl enable devtoolset-7 "./configure --prefix=/opt/python${PYTHON_MINOR} --with-libxml-prefix=/opt/python${PYTHON_MINOR} --without-python --without-crypto --disable-static" && \
  scl enable devtoolset-7 "make -j$(nproc)" && \
  scl enable devtoolset-7 "make install" && \
  cd /tmp && rm -rf libxslt-1.1.42*

# Stage 2 - build python using the generated definition
FROM openssl_sqlite_builder AS python_builder
ARG PYTHON_VERSION
ARG PYTHON_MINOR
RUN scl enable devtoolset-7 "python-build --verbose ${PYTHON_VERSION}-c6-relocatable /opt/python${PYTHON_MINOR}"

# Stage 3 - install the bundled pip packages from requirements.txt.
# Runs before patchelf because we want the rpath-rewrite step to also fix
# any C extensions pip builds from source against /opt/python${MINOR}/lib.
# LD_LIBRARY_PATH is set explicitly because the binary's RPATH hasn't been
# rewritten yet at this point.
#
# We source the devtoolset-7 enable script instead of wrapping each command in
# `scl enable devtoolset-7 "..."`: the wrapper form can swallow the wrapped
# command's non-zero exit status, so a failed source build (e.g. a C-extension
# with no glibc-2.12 wheel and unbuildable against CentOS 6's ancient system
# libs) would sail past this stage and only surface ~250 lines later as a
# confusing ModuleNotFoundError in a downstream relocated-tarball test stage.
# Sourcing makes pip's exit code the RUN's exit code, so the build fails here
# with the real error.
#
# PATH is prepended with ${PREFIX}/bin so lxml's build discovers the xml2-config
# / xslt-config of the libxml2 + libxslt we built into the prefix (there is no
# system xml2-config — we deliberately did not install libxml2-devel), and links
# lxml.etree against those shared libs. relocate.py later rewrites its RPATH to
# ${PREFIX}/lib, so the bundled libxml2/libxslt resolve on the target hosts.
FROM python_builder AS python_with_packages
ARG PYTHON_MINOR
COPY requirements.txt /tmp/requirements.txt
RUN export PREFIX=/opt/python${PYTHON_MINOR} && \
  . /opt/rh/devtoolset-7/enable && \
  export PATH="${PREFIX}/bin:${PATH}" && \
  export LD_LIBRARY_PATH="${PREFIX}/lib:${LD_LIBRARY_PATH}" && \
  export PKG_CONFIG_PATH="${PREFIX}/lib/pkgconfig" && \
  ${PREFIX}/bin/pip${PYTHON_MINOR} install --no-cache-dir --upgrade pip && \
  ${PREFIX}/bin/pip${PYTHON_MINOR} install --no-cache-dir -r /tmp/requirements.txt && \
  echo "--- verifying every requirement is installed (fail here, not downstream) ---" && \
  ${PREFIX}/bin/python${PYTHON_MINOR} -c "import re; from importlib.metadata import distributions; have={d.metadata['Name'].lower().replace('_','-') for d in distributions()}; want=[re.split(r'[<>=!~;\[ ]', l.split('#',1)[0].strip())[0] for l in open('/tmp/requirements.txt') if l.split('#',1)[0].strip()]; miss=[w for w in want if w.lower().replace('_','-') not in have]; __import__('sys').exit('ERROR: listed in requirements.txt but not installed: '+', '.join(miss)) if miss else print('verified installed:', ', '.join(want))" && \
  find ${PREFIX} -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true && \
  rm -f /tmp/requirements.txt

# Stage 4 - bundle CentOS-6-only system shared libraries into the prefix.
# Several lib-dynload modules (readline, _curses, _gdbm, _ctypes, _uuid)
# and bin/sqlite3 NEED sonames that only exist on CentOS 6 (libreadline.so.6,
# libtinfo.so.5, libffi.so.5, etc.). Copying them into ${PREFIX}/lib makes the
# tarball runnable on modern distros too — RPATH already covers that dir.
# Done before the patchelf stage so relocate.py's prefix walk picks these up
# and rewrites their RPATH alongside everything else.
FROM python_with_packages AS python_with_bundled_system_libs
ARG PYTHON_MINOR
COPY scripts/bundle-system-libs.sh /usr/local/bin/bundle-system-libs.sh
RUN sh /usr/local/bin/bundle-system-libs.sh /opt/python${PYTHON_MINOR}

# Stage 5 - rewrite RPATHs and shebangs so the install can be relocated.
# Done in two phases because patchelf can't modify a file that's mapped
# into a running process (ETXTBSY): if we ran patchelf via the bundled
# python, it could not patch the python binary or libpython.so itself.
# Phase 1: bundled python plans the work — rewrites bin/* shebangs in
# place (regular files, no ELF lock) and emits a shell script of patchelf
# invocations using os.path.relpath to compute paths to lib/.
# Phase 2: sh runs that script after python has exited, releasing all
# file mappings, so patchelf can safely modify the binary, libpython.so,
# the bundled OpenSSL/SQLite libs, and every other .so under the prefix.
FROM python_with_bundled_system_libs AS patch_to_make_relocatable
ARG PYTHON_MINOR
RUN yum install -y epel-release && yum install -y patchelf
COPY scripts/relocate.py /usr/local/bin/relocate.py
# LD_LIBRARY_PATH is scoped to just the python invocation, NOT the `sh`
# that drives phase 2. /bin/sh on CentOS 6 NEEDs libtinfo.so.5; if
# LD_LIBRARY_PATH points at ${PREFIX}/lib (where we just bundled it)
# sh maps the bundled libtinfo, phase 2's patchelf modifies that file
# in place, and sh segfaults on exit running destructors against the
# now-stale mapping. Letting sh resolve libtinfo from /usr/lib64
# avoids the conflict.
RUN export PREFIX=/opt/python${PYTHON_MINOR} && \
  LD_LIBRARY_PATH="${PREFIX}/lib" ${PREFIX}/bin/python${PYTHON_MINOR} \
    /usr/local/bin/relocate.py ${PREFIX} ${PYTHON_MINOR} /tmp/relocate-patches.sh && \
  sh /tmp/relocate-patches.sh && \
  rm -f /tmp/relocate-patches.sh

# Stage 6 - copy the patched install to a fresh build env and run CPython's
# own stdlib regression tests against the relocated tree. This exercises
# real behavior in every C extension whose NEEDED entries point at our
# bundled libs (TLS handshakes, sqlite db operations, real bz2/lzma
# round-trips, etc.) — strictly stronger than checking that the .so files
# load. The third-party smoke tests (requests/pycryptodome/certifi) and
# helper-binary version prints stay because the stdlib suite doesn't
# cover them.
FROM openssl_sqlite_builder AS test_relocatable
ARG PYTHON_MINOR
RUN mkdir -p /opt/very/relocated
WORKDIR /opt/very/relocated
COPY --from=patch_to_make_relocatable /opt/python${PYTHON_MINOR} /opt/very/relocated/python${PYTHON_MINOR}
COPY scripts/run-sqlite3-tests.sh /usr/local/bin/run-sqlite3-tests.sh
RUN BIN=/opt/very/relocated/python${PYTHON_MINOR}/bin && \
  PY=${BIN}/python${PYTHON_MINOR} && \
  ${PY} --version && \
  ${PY} -c "import ssl; print('OpenSSL:', ssl.OPENSSL_VERSION)" && \
  ${PY} -c "import sqlite3; print('SQLite:', sqlite3.sqlite_version)" && \
  ${PY} -c "import zlib; print('zlib:', zlib.ZLIB_VERSION)" && \
  ${PY} -c "import sys; print('Platform:', sys.platform)" && \
  TERM=xterm ${PY} -m test -j$(nproc) --quiet \
    test_lzma test_bz2 test_zlib \
    test_uuid test_ssl test_hashlib \
    test_decimal test_dbm test_dbm_gnu test_readline \
    test_curses test_crypt && \
  sh /usr/local/bin/run-sqlite3-tests.sh ${PY} && \
  ${PY} -c "import ctypes; libc=ctypes.CDLL('libc.so.6'); libc.getpid.restype=ctypes.c_int; assert libc.getpid() > 0; print('ctypes via libffi: OK')" && \
  ${PY} -c "import certifi; print('certifi:', certifi.where())" && \
  ${PY} -c "import requests; print('requests:', requests.__version__)" && \
  ${PY} -c "from Crypto.Cipher import AES; print('pycryptodome AES: OK')" && \
  ${PY} -c "import lxml.etree as e; print('lxml OK:', e.LXML_VERSION, 'libxml2:', e.LIBXML_VERSION)" && \
  ${BIN}/openssl version && \
  ${BIN}/sqlite3 -version && \
  touch /tmp/relocatable-tests-passed

# Stage 7 - second verification on a current Ubuntu LTS. Catches regressions
# where a NEEDED soname only exists on CentOS 6 and isn't bundled — the
# CentOS 6 test stage above silently passes those because the host happens
# to have the libs in /usr/lib64. This stage runs the same imports against
# a host that has none of those CentOS-6-vintage sonames, so any unbundled
# system dep surfaces as an ImportError or sqlite3 dynamic-link failure.
FROM ubuntu:26.04 AS test_relocatable_modern
ARG PYTHON_MINOR
RUN apt-get update && \
  apt-get install -y --no-install-recommends ca-certificates && \
  rm -rf /var/lib/apt/lists/*
RUN mkdir -p /opt/very/relocated
WORKDIR /opt/very/relocated
COPY --from=patch_to_make_relocatable /opt/python${PYTHON_MINOR} /opt/very/relocated/python${PYTHON_MINOR}
COPY scripts/run-sqlite3-tests.sh /usr/local/bin/run-sqlite3-tests.sh
RUN BIN=/opt/very/relocated/python${PYTHON_MINOR}/bin && \
  PY=${BIN}/python${PYTHON_MINOR} && \
  ${PY} --version && \
  ${PY} -c "import ssl; print('OpenSSL:', ssl.OPENSSL_VERSION)" && \
  ${PY} -c "import sqlite3; print('SQLite:', sqlite3.sqlite_version)" && \
  ${PY} -c "import zlib; print('zlib:', zlib.ZLIB_VERSION)" && \
  TERM=xterm ${PY} -m test -j$(nproc) --quiet \
    test_lzma test_bz2 test_zlib \
    test_uuid test_ssl test_hashlib \
    test_decimal test_dbm test_dbm_gnu test_readline \
    test_curses test_crypt && \
  sh /usr/local/bin/run-sqlite3-tests.sh ${PY} && \
  ${PY} -c "import ctypes; libc=ctypes.CDLL('libc.so.6'); libc.getpid.restype=ctypes.c_int; assert libc.getpid() > 0; print('ctypes via libffi: OK')" && \
  ${PY} -c "import certifi; print('certifi:', certifi.where())" && \
  ${PY} -c "import requests; print('requests:', requests.__version__)" && \
  ${PY} -c "from Crypto.Cipher import AES; print('pycryptodome AES: OK')" && \
  ${PY} -c "import lxml.etree as e; print('lxml OK:', e.LXML_VERSION, 'libxml2:', e.LIBXML_VERSION)" && \
  ${BIN}/openssl version && \
  ${BIN}/sqlite3 -version && \
  touch /tmp/relocatable-tests-modern-passed

# Stage 8 - third verification on Rocky Linux 9, which is one of the
# deployment targets. Same import suite as the Ubuntu stage; rocky 9 ships
# different soname versions (libreadline.so.8, libtinfo.so.6, libffi.so.8,
# libgdbm.so.6, ...) than CentOS 6, so this exercises the bundled-libs
# path on a real RHEL-family modern host.
FROM rockylinux:9 AS test_relocatable_rocky9
ARG PYTHON_MINOR
# libxcrypt-compat provides libcrypt.so.1 (Rocky 9's base libxcrypt only
# ships libcrypt.so.2). The bundled python links against libcrypt.so.1.
RUN dnf install -y --setopt=install_weak_deps=False ca-certificates libxcrypt-compat && \
  dnf clean all
RUN mkdir -p /opt/very/relocated
WORKDIR /opt/very/relocated
COPY --from=patch_to_make_relocatable /opt/python${PYTHON_MINOR} /opt/very/relocated/python${PYTHON_MINOR}
COPY scripts/run-sqlite3-tests.sh /usr/local/bin/run-sqlite3-tests.sh
RUN BIN=/opt/very/relocated/python${PYTHON_MINOR}/bin && \
  PY=${BIN}/python${PYTHON_MINOR} && \
  ${PY} --version && \
  ${PY} -c "import ssl; print('OpenSSL:', ssl.OPENSSL_VERSION)" && \
  ${PY} -c "import sqlite3; print('SQLite:', sqlite3.sqlite_version)" && \
  ${PY} -c "import zlib; print('zlib:', zlib.ZLIB_VERSION)" && \
  TERM=xterm ${PY} -m test -j$(nproc) --quiet \
    test_lzma test_bz2 test_zlib \
    test_uuid test_ssl test_hashlib \
    test_decimal test_dbm test_dbm_gnu test_readline \
    test_curses test_crypt && \
  sh /usr/local/bin/run-sqlite3-tests.sh ${PY} && \
  ${PY} -c "import ctypes; libc=ctypes.CDLL('libc.so.6'); libc.getpid.restype=ctypes.c_int; assert libc.getpid() > 0; print('ctypes via libffi: OK')" && \
  ${PY} -c "import certifi; print('certifi:', certifi.where())" && \
  ${PY} -c "import requests; print('requests:', requests.__version__)" && \
  ${PY} -c "from Crypto.Cipher import AES; print('pycryptodome AES: OK')" && \
  ${PY} -c "import lxml.etree as e; print('lxml OK:', e.LXML_VERSION, 'libxml2:', e.LIBXML_VERSION)" && \
  ${BIN}/openssl version && \
  ${BIN}/sqlite3 -version && \
  touch /tmp/relocatable-tests-rocky9-passed

# Stage 9 (final) - build the release tarball. Pulls a marker file from each
# test stage so buildx is forced to schedule all three; if any set of
# relocation tests fails the whole build fails before producing an archive.
FROM patch_to_make_relocatable AS final_archive_env
ARG PYTHON_VERSION
ARG PYTHON_MINOR
COPY --from=test_relocatable /tmp/relocatable-tests-passed /tmp/relocatable-tests-passed
COPY --from=test_relocatable_modern /tmp/relocatable-tests-modern-passed /tmp/relocatable-tests-modern-passed
COPY --from=test_relocatable_rocky9 /tmp/relocatable-tests-rocky9-passed /tmp/relocatable-tests-rocky9-passed
RUN cd /opt && \
  tar -czf python${PYTHON_VERSION}-c6-relocatable.tar.gz python${PYTHON_MINOR} && \
  echo "python build complete - tar created at /opt/python${PYTHON_VERSION}-c6-relocatable.tar.gz"
