# Build args: PYTHON_VERSION (e.g. 3.10.20) is the only required input.
# PYTHON_MINOR (e.g. 3.10) is derived by build.sh / the workflow and passed in
# so it can be used in COPY --from paths (which require build-time literals).
ARG PYTHON_VERSION=3.10.19
ARG PYTHON_MINOR=3.10
# pyenv is pinned to a release tag so the upstream python-build definitions
# we consume are reproducible.
ARG PYENV_REF=v2.6.28

FROM centos:6 AS openssl_sqlite_builder
ARG PYTHON_VERSION
ARG PYTHON_MINOR
ARG PYENV_REF

# CentOS 6 reached EOL, so we need to use vault.centos.org
RUN sed -i 's|^mirrorlist=|#mirrorlist=|g' /etc/yum.repos.d/CentOS-Base.repo && \
  sed -i 's|^#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-Base.repo

# Install SCL repository for newer GCC and fix its mirrors too
RUN yum install -y centos-release-scl && \
  rm -f /etc/yum.repos.d/CentOS-SCLo-scl*.repo && \
  cat > /etc/yum.repos.d/CentOS-SCLo-scl.repo << 'REPOEOF'
[centos-sclo-rh]
name=CentOS-6 - SCLo rh
baseurl=https://vault.centos.org/6.10/sclo/x86_64/rh/
gpgcheck=1
enabled=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-SCLo

[centos-sclo-sclo]
name=CentOS-6 - SCLo sclo
baseurl=https://vault.centos.org/6.10/sclo/x86_64/sclo/
gpgcheck=1
enabled=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-SCLo
REPOEOF
RUN yum clean all

# Install build dependencies and devtoolset-7 (GCC 7).
# Python 3.10 requires GCC 4.8+ and CentOS 6 only has GCC 4.4 by default.
RUN yum install -y \
  devtoolset-7-gcc \
  devtoolset-7-gcc-c++ \
  make \
  git \
  wget \
  curl \
  tar \
  bzip2 \
  xz \
  patch \
  perl \
  zlib-devel \
  bzip2-devel \
  sqlite-devel \
  libffi-devel \
  readline-devel \
  ncurses-devel \
  gdbm-devel \
  xz-devel \
  tk-devel && \
  yum clean all

RUN mkdir -p /opt/python${PYTHON_MINOR}

# Clone pyenv at a pinned release tag so upstream python-build defs are reproducible.
RUN git clone --branch "${PYENV_REF}" --depth=1 https://github.com/pyenv/pyenv.git /opt/pyenv && \
  ln -s /opt/pyenv/plugins/python-build/bin/python-build /usr/local/bin/python-build

# Generate the relocatable build definition by concatenating our preamble
# (env vars pointing the build at our /opt/python${PYTHON_MINOR}/{lib,include}
# where we install OpenSSL 1.1.1 and SQLite below, plus --enable-shared) on top
# of the upstream pyenv definition for ${PYTHON_VERSION}. Upstream's
# prefer_openssl3 / mac install_package calls are inert on Linux, so plain
# concatenation is sufficient.
RUN set -e; \
  UPSTREAM=/opt/pyenv/plugins/python-build/share/python-build/${PYTHON_VERSION}; \
  if [ ! -f "${UPSTREAM}" ]; then \
    echo "ERROR: pyenv ${PYENV_REF} has no definition for Python ${PYTHON_VERSION} at ${UPSTREAM}" >&2; \
    exit 1; \
  fi; \
  DEF=/opt/pyenv/plugins/python-build/share/python-build/${PYTHON_VERSION}-c6-relocatable; \
  { \
    echo '# Generated by python-centos6-builder Dockerfile.'; \
    echo "# Wraps upstream pyenv ${PYENV_REF} definition for Python ${PYTHON_VERSION}."; \
    echo 'export PYTHON_BUILD_CONFIGURE_WITH_OPENSSL=1'; \
    echo 'export PYTHON_CFLAGS="-DOPENSSL_NO_SSL3${PYTHON_CFLAGS:+ $PYTHON_CFLAGS}"'; \
    echo 'export PYTHON_CONFIGURE_OPTS="--enable-shared --with-ensurepip=install${PYTHON_CONFIGURE_OPTS:+ $PYTHON_CONFIGURE_OPTS}"'; \
    echo "export CPPFLAGS=\"-I/opt/python${PYTHON_MINOR}/include\""; \
    echo "export PKG_CONFIG_PATH=\"/opt/python${PYTHON_MINOR}/lib/pkgconfig\""; \
    echo "export LD_LIBRARY_PATH=\"/opt/python${PYTHON_MINOR}/lib\""; \
    echo 'prefer_openssl11'; \
    echo ''; \
    cat "${UPSTREAM}"; \
  } > "${DEF}"; \
  echo "--- generated ${DEF} ---"; \
  cat "${DEF}"

# Build SQLite 3 (CentOS 6 has 3.6.20, but Python 3.10 needs 3.7.15+)
RUN cd /tmp && \
  wget https://www.sqlite.org/2024/sqlite-autoconf-3450200.tar.gz && \
  tar xzf sqlite-autoconf-3450200.tar.gz && \
  cd sqlite-autoconf-3450200 && \
  scl enable devtoolset-7 "./configure --prefix=/opt/python${PYTHON_MINOR}" && \
  scl enable devtoolset-7 "make -j$(nproc)" && \
  scl enable devtoolset-7 "make install" && \
  cd /tmp && rm -rf sqlite-autoconf-3450200*

# Build OpenSSL 1.1.1w (Python 3.10 requires OpenSSL 1.1.1+, CentOS 6 has 1.0.x)
RUN cd /tmp && \
  wget https://www.openssl.org/source/openssl-1.1.1w.tar.gz && \
  tar xzf openssl-1.1.1w.tar.gz && \
  cd openssl-1.1.1w && \
  scl enable devtoolset-7 "./config --prefix=/opt/python${PYTHON_MINOR} --openssldir=/opt/python${PYTHON_MINOR}/ssl shared zlib" && \
  scl enable devtoolset-7 "make -j$(nproc)" && \
  scl enable devtoolset-7 "make install_sw" && \
  cd /tmp && rm -rf openssl-1.1.1w*

# Stage 2 - build python using the generated definition
FROM openssl_sqlite_builder AS python_builder
ARG PYTHON_VERSION
ARG PYTHON_MINOR
RUN scl enable devtoolset-7 "python-build --verbose ${PYTHON_VERSION}-c6-relocatable /opt/python${PYTHON_MINOR}"

# Stage 3 - patch rpath so the python executable + dynload modules find their
# libs relative to themselves, making the install relocatable.
FROM python_builder AS patch_to_make_relocatable
ARG PYTHON_MINOR
RUN yum install -y epel-release && yum install -y patchelf
RUN patchelf --set-rpath '$ORIGIN/../lib' /opt/python${PYTHON_MINOR}/bin/python${PYTHON_MINOR}
RUN find /opt/python${PYTHON_MINOR}/lib/python${PYTHON_MINOR}/lib-dynload -name "*.so" | \
  xargs -n1 patchelf --set-rpath '$ORIGIN/../..'

# Stage 4 - copy the patched install to a fresh build env and exercise modules
# that load shared libs to verify rpath patching works after relocation.
FROM openssl_sqlite_builder AS test_relocatable
ARG PYTHON_MINOR
RUN mkdir -p /opt/very/relocated
WORKDIR /opt/very/relocated
COPY --from=patch_to_make_relocatable /opt/python${PYTHON_MINOR} /opt/very/relocated/python${PYTHON_MINOR}
RUN /opt/very/relocated/python${PYTHON_MINOR}/bin/python${PYTHON_MINOR} --version && \
  /opt/very/relocated/python${PYTHON_MINOR}/bin/python${PYTHON_MINOR} -c "import ssl; print('OpenSSL:', ssl.OPENSSL_VERSION)" && \
  /opt/very/relocated/python${PYTHON_MINOR}/bin/python${PYTHON_MINOR} -c "import sqlite3; print('SQLite:', sqlite3.sqlite_version)" && \
  /opt/very/relocated/python${PYTHON_MINOR}/bin/python${PYTHON_MINOR} -c "import zlib; print('zlib:', zlib.ZLIB_VERSION)" && \
  /opt/very/relocated/python${PYTHON_MINOR}/bin/python${PYTHON_MINOR} -c "import sys; print('Platform:', sys.platform)" && \
  /opt/very/relocated/python${PYTHON_MINOR}/bin/python${PYTHON_MINOR} -c "import ctypes; print('ctypes: OK')" && \
  /opt/very/relocated/python${PYTHON_MINOR}/bin/python${PYTHON_MINOR} -c "import _decimal; print('decimal: OK')" && \
  /opt/very/relocated/python${PYTHON_MINOR}/bin/python${PYTHON_MINOR} -c "import _hashlib; print('hashlib: OK')" && \
  /opt/very/relocated/python${PYTHON_MINOR}/bin/python${PYTHON_MINOR} -c "import _bz2; print('bz2: OK')" && \
  /opt/very/relocated/python${PYTHON_MINOR}/bin/python${PYTHON_MINOR} -c "import _lzma; print('lzma: OK')" && \
  /opt/very/relocated/python${PYTHON_MINOR}/bin/python${PYTHON_MINOR} -c "import _uuid; print('uuid: OK')" && \
  touch /tmp/relocatable-tests-passed

# Stage 5 (final) - build the release tarball. Pulls a marker file from the
# test stage so buildx is forced to schedule it; if relocation tests fail the
# whole build fails before producing an archive.
FROM patch_to_make_relocatable AS final_archive_env
ARG PYTHON_VERSION
ARG PYTHON_MINOR
COPY --from=test_relocatable /tmp/relocatable-tests-passed /tmp/relocatable-tests-passed
RUN cd /opt && \
  tar -czf python${PYTHON_VERSION}-c6-relocatable.tar.gz python${PYTHON_MINOR} && \
  echo "python build complete - tar created at /opt/python${PYTHON_VERSION}-c6-relocatable.tar.gz"
