name: Build and Release Python Tarball

permissions:
  contents: write
  packages: write
  actions: write
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install mise
        uses: jdx/mise-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Build Python tarball
        run: mise run build

      - name: Verify tarball exists
        run: |
          ls -lh python3.10.18-c6-relocatable.tar.gz
          echo "Tarball size: $(du -h python3.10.18-c6-relocatable.tar.gz | cut -f1)"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: |
            ## Relocatable Python 3.10.18 for CentOS 6

            This release contains a relocatable Python 3.10.18 build compatible with CentOS 6 (glibc 2.12).

            ### Installation

            1. Download `python3.10.18-c6-relocatable.tar.gz`
            2. Extract to your desired location: `tar -xzf python3.10.18-c6-relocatable.tar.gz -C /opt/`
            3. Use Python: `/opt/python3.9/bin/python3.9 --version`

            ### Features

            - ✅ CentOS 6 Compatible (glibc 2.12)
            - ✅ Relocatable (can be extracted anywhere)
            - ✅ Includes OpenSSL 1.1.1, all standard library modules, and pip

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./python3.10.18-c6-relocatable.tar.gz
          asset_name: python3.10.18-c6-relocatable.tar.gz
          asset_content_type: application/gzip
